version: '3'
  
services:
  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    restart: always
