version: '3'

networks:
  inception:

volumes:
  site:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tdi-leo.42.fr/data/site/'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tdi-leo.42.fr/data/database/'

services:

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: wordpress
    restart: always
    networks:
      - inception
    volumes:
      - site:/var/www/html/
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    env_file:
      - .env
    container_name: nginx
    restart: always
    networks:
      - inception
    volumes:
      - site:/var/www/html/
    depends_on:
      - wordpress
    
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: mariadb
    restart: always
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql/